baseURL: "https://blog.fifsky.com"
languageCode: "zh-CN"
title: BLOG
paginate: 5
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: Doing is better than saying.
    description: "ExampleSite description"
    author: fifsky

    images: "<link or path of image for opengraph, twitter-cards>"

    ShowReadingTime: true
    ShowShareButtons: true
    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false
 
    assets:
        favicon: "logo.png"
        favicon16x16: "logo.png"
        favicon32x32: "logo.png"
        apple_touch_icon: "logo.png"
        safari_pinned_tab: "logo.png"

    label:
        text: "Home"
        icon: /logo.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: 朝花夕拾
        # imageUrl: '<img location>'
        # imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: About
              url: about

    socialIcons:
        - name: twitter
          url: "https://twitter.com/caixudong"
        - name: github
          url: "https://github.com/fifsky"

menu:
    main:
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
